# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 18:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='album',
            name='description',
            field=models.TextField(default=django.utils.timezone.now, help_text='Enter valid description', max_length=100),
            preserve_default=False,
        ),
    ]
