# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 01:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import memories.apps.album.models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0003_auto_20170621_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=memories.apps.album.models.uploader_path),
        ),
        migrations.AlterField(
            model_name='album',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='albums', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
